language: php

php:
  - 7.4

addons:
  chrome: stable

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan serve

before_install:
  - mysql -e 'CREATE DATABASE laravel;'

script:
  - php artisan test

services:
  - mysql